name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'packages/auth/**'

defaults:
  run:
    working-directory: packages/auth

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Build a project
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build

      # Deploy to AWS
      - uses: chrislennon/action-aws-cli@v1.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - run: aws s3 sync ./dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/auth/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Invalidate a CloudFront distribution
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/auth/latest/index.html"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
